# factory/agents/code_agent.py
from .base_agent import BaseAgent, AgentTask, AgentResult
import uuid

class CodeAgent(BaseAgent):
    def __init__(self):
        super().__init__("CodeAgent", "code_generator")
    
    async def process(self, task: AgentTask) -> AgentResult:
        prompt = task.input_data.get("prompt", "")
        
        generated_code = f'''
# AI-Generated Code
# Prompt: {prompt}
# Generated by: {self.name}

class GeneratedApplication:
    def __init__(self):
        print("AI Factory Generated Application")
    
    def run(self):
        return "Application is running!"

if __name__ == "__main__":
    app = GeneratedApplication()
    app.run()
'''
        
        return AgentResult(
            task_id=task.task_id,
            agent_type=self.agent_type,
            output_data={"code": generated_code, "language": "python"},
            confidence_score=0.85,
            success=True
        )
    
    def can_handle(self, task_type: str) -> bool:
        return task_type in ["generate_code", "create_app"]
