# backend/app/api/v1/agents.py
from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel
from typing import Dict, Any, List, Optional
import sys
from pathlib import Path

factory_path = Path(__file__).parent.parent.parent.parent / "factory"
if str(factory_path) not in sys.path:
    sys.path.insert(0, str(factory_path))

router = APIRouter()

class AgentExecuteRequest(BaseModel):
    agent_type: str
    task_type: str
    input_data: Dict[str, Any] = {}

class GenerateRequest(BaseModel):
    prompt: str
    entity_name: str = "item"

@router.get("/")
async def list_agents():
    return {"agents": ["code_generator", "architect", "backend", "frontend", "database", "qa", "security", "devops"]}

@router.post("/execute")
async def execute_agent(request: AgentExecuteRequest):
    return {
        "success": True,
        "agent_type": request.agent_type,
        "task_type": request.task_type,
        "output": {
            "message": f"Agent {request.agent_type} executed {request.task_type}",
            "code": f"# Generated code for: {request.input_data.get('prompt', 'task')}\n\nclass GeneratedApp:\n    def __init__(self):\n        print('AI Factory Generated Application')\n    \n    def run(self):\n        return 'Application is running!'",
            "confidence": 85
        },
        "task_id": "simulated-123"
    }

@router.post("/generate")
async def generate_code(request: GenerateRequest):
    prompt = request.prompt
    entity_name = request.entity_name
    
    generated_code = f'''# AI-Generated Code
# Prompt: {prompt}
# Generated by: AI Software Factory v1.3

class {entity_name.capitalize()}:
    """Auto-generated class based on prompt: {prompt}"""
    
    def __init__(self):
        print(f"Initializing {entity_name}...")
        self.data = []
    
    def create(self, item):
        """Create a new item"""
        self.data.append(item)
        return {{"status": "created", "id": len(self.data)}}
    
    def get_all(self):
        """Get all items"""
        return {{"items": self.data, "count": len(self.data)}}
    
    def update(self, id, item):
        """Update an existing item"""
        if 1 <= id <= len(self.data):
            self.data[id-1] = item
            return {{"status": "updated", "id": id}}
        return {{"error": "Item not found"}}
    
    def delete(self, id):
        """Delete an item"""
        if 1 <= id <= len(self.data):
            self.data.pop(id-1)
            return {{"status": "deleted", "id": id}}
        return {{"error": "Item not found"}}

# Example usage
if __name__ == "__main__":
    app = {entity_name.capitalize()}()
    print(app.create({{"name": "Sample {{entity_name}}"}}))
    print(app.get_all())
'''
    
    return {
        "success": True,
        "agent_type": "code_generator",
        "output": {
            "code": generated_code,
            "language": "python",
            "files": [f"{entity_name}.py", f"test_{entity_name}.py"],
            "classes": [f"{entity_name.capitalize()}"],
            "methods": ["create", "get_all", "update", "delete"]
        },
        "confidence": 90,
        "task_id": f"gen_{entity_name.lower()}"
    }

@router.post("/generate-form")
async def generate_code_form(prompt: str = Query(...), entity_name: str = Query("item")):
    """Alternative endpoint using form data for backward compatibility"""
    request = GenerateRequest(prompt=prompt, entity_name=entity_name)
    return await generate_code(request)